%{
    split the data into 15 min segments
%}
clear all
close all
%% set path
datapath = 'Y:\Group_folder\foryaning\maze_bea_20240702';
savepath = 'Y:\Group_folder\foryaning\maze_bea_20240712_split';
%% load data
csvFolder = fullfile(datapath);
dirOutput = dir(fullfile(csvFolder,'*.csv'));
csvNames = {dirOutput.name}';
%% split data
fs = 30;
cut_size = 10*60*fs;
tic
for k = 1:size(csvNames,1)
    %% load name
    csvname = csvNames{k,1};
    videoname = [csvname(1,1:(end-4)),'.mp4'];
    %% load data
    csvdata = readtable([datapath,'\',csvname]);
    vidobj = VideoReader([datapath,'\',videoname]);

    csv_data = csvdata.Variables;
    %% generate cut list
    datasize = size(csvdata,1);

    start_list = 1:cut_size:datasize;
    end_list = cut_size:cut_size:datasize;

    savelist = [start_list',end_list'];
    %% cut data
    for m = 1:size(savelist,1)
        tempstart = savelist(m,1);
        tempend = savelist(m,2);

        seldata = num2cell(csv_data(tempstart:tempend,:));

        savecsvname = [csvname(1:(end-4)),'-',...
            num2str(tempstart),'_',num2str(tempend),...
            '.csv'];

        savevideoname = [videoname(1:(end-4)),'-',...
            num2str(tempstart),'_',num2str(tempend),...
            '.mp4'];

        %% save csv
        csvtitle = {...
            'scorer',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000',...
            'DLC_resnet50_Young_BL6Oct20shuffle1_400000';...
            'bodyparts',...
            'Ear_left',...
            'Ear_left',...
            'Ear_left',...
            'Ear_right',...
            'Ear_right',...
            'Ear_right',...
            'Nose',...
            'Nose',...
            'Nose',...
            'Head_center',...
            'Head_center',...
            'Head_center',...
            'Center',...
            'Center',...
            'Center',...
            'Lateral_left',...
            'Lateral_left',...
            'Lateral_left',...
            'Lateral_right',...
            'Lateral_right',...
            'Lateral_right',...
            'Tail_base',...
            'Tail_base',...
            'Tail_base',...
            'Tail1',...
            'Tail1',...
            'Tail1',...
            'Tail2',...
            'Tail2',...
            'Tail2',...
            'Tail_end',...
            'Tail_end',...
            'Tail_end';...
            'coords',...
            'x',...
            'y',...
            'likelihood',...
            'x',...
            'y',...
            'likelihood',...
            'x',...
            'y',...
            'likelihood',...
            'x',...
            'y',...
            'likelihood',...
            'x',...
            'y',...
            'likelihood',...
            'x',...
            'y',...
            'likelihood',...
            'x',...
            'y',...
            'likelihood',...
            'x',...
            'y',...
            'likelihood',...
            'x',...
            'y',...
            'likelihood',...
            'x',...
            'y',...
            'likelihood',...
            'x',...
            'y',...
            'likelihood'};

        savecsvdata = [csvtitle;seldata];
        xlswrite([savepath,'\',savecsvname],savecsvdata)
        %% save videos
        writeobj = VideoWriter(...
            [savepath,'\',savevideoname],'MPEG-4');
        open(writeobj)
        for n = tempstart:tempend
            frame = read(vidobj,n);
            writeVideo(writeobj,frame)
        end
        close(writeobj)
    end
    %% show time
    disp(k)
    toc
end












